version: '3.9'
services:
  postgres:
    image: postgres:12.18-alpine3.19
    restart: always
    # restart: on-failure
    shm_size: 128mb
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: sProject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    networks:
      - app_network
  
  php:
    build:
      context: .
      target: app_php
    image: sf-docker/php:dev
    restart: on-failure
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    depends_on:
      - postgres
    volumes:
      - .:/app:rw,cached
    networks:
      - app_network

  nginx:
    build:
      context: .
      target: app_nginx
    image: sf-docker/nginx:dev
    restart: on-failure
    volumes:
      - ./public:/app/public:rowww
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network

networks:
  app_network:
    driver: "bridge"
